export const CREDIT_CARD_WIDTH_INCH = 3.37;
export const CREDIT_CARD_HEIGHT_INCH = 2.13;
export const CREDIT_CARD_ASPECT_RATIO = CREDIT_CARD_WIDTH_INCH / CREDIT_CARD_HEIGHT_INCH;

export const DOLLAR_BILL_WIDTH_INCH = 6.14;
export const DOLLAR_BILL_HEIGHT_INCH = 2.61;
export const DOLLAR_BILL_ASPECT_RATIO = DOLLAR_BILL_WIDTH_INCH / DOLLAR_BILL_HEIGHT_INCH;

export const MM_TO_INCH = 1 / 25.4;
export const INCH_TO_MM = 25.4;